# 参数解释。注意冒号或短横线后必须接一个空格，不能省略
#  font:
#    default: 西文字体
#    eastern: 中文字体
#  indent: 首行缩进，如 2x
#  size: 字体大小，如 12pt
#  line-spacing: 行距，如 1.5x 表示 1.5 倍行距
#  space:
#    before 段前空格，单位pt
#    after: 段后空格，单位pt
#  color: RGB颜色的16进制值，如 000000 => 黑色
#  extra: 可选，额外的样式，包含下列量，有则设置，无则不设置
#  - bold 加粗
#  - italic 斜体
#  - underline 下划线
#  - strike 删除线
#  - highlight 高亮

title:
  font:
    default: Times New Roman
    east-asian: 黑体
  size: 16pt
  align: center

h1:
  font:
    default: Times New Roman
    east-asian: 黑体
  size: 14pt
  line-spacing: 1.5x
  space-before-after: 0 0

h2:
  font:
    default: Times New Roman
    east-asian: 黑体
  size: 12pt
  line-spacing: 1.5x
  space-before-after: 0 0

h3:
  font:
    default: Times New Roman
    east-asian: 楷体
  size: 12pt
  line-spacing: 1.5x
  space-before-after: 0 0

normal:
  font:
    default: Times New Roman
    east-asian: 宋体
  indent: 2x
  size: 12pt
  line-spacing: 1.5x  # 1.5倍行距
  color: 000000       # RGB Color in Hex, 000000 => black
