# 图片下载配置文件
# Image download configuration

# 是否使用浏览器Cookie（解决需要登录才能访问的图片）
use_browser_cookies: true

# 是否验证SSL证书（设置为false可以解决自签名证书问题）
verify_ssl: false

# 下载超时时间（秒）
timeout: 15

# 自定义请求头
custom_headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  # 可以添加更多自定义头，例如：
  # Referer: "https://your-site.com"
  # Authorization: "Bearer your-token"

# 优先使用的浏览器Cookie（按优先级排序）
preferred_browsers:
  - chrome
  - firefox
  - edge

# 图片下载重试设置
retry:
  # 最大重试次数
  max_attempts: 3
  # 重试间隔（秒）
  delay: 1

# 调试模式（显示详细的下载信息）
debug: true 